destination: docs

collections:
  services:
    output: false
    sort_by: order
  articles:
    output: false
    sort_by: order
  chapters:
    output: false
    sort_by: order
  presentations:
    output: false
    sort_by: year
    sort_direction: descending


